name: npm publish Vonage

on:
  push:
    paths:
      - platforms/platform-vonage/**

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - run: npm run preparePublish

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_PACKAGES}}
